<a href="https://colab.research.google.com/github/mars8577/CSC.htm/blob/main/ata_cleaning_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Intro to Data Science: Pandas Data Cleaning Practice

In this notebook, you will practice cleaning a messy dataset using pandas.


## Your goals:
1. Load the messy student survey dataset below into a DataFrame.
2. Inspect the data using pandas methods.
3. Clean column names.
4. Remove duplicate rows.
5. Fix inconsistent text formatting.
6. Convert columns to appropriate data types.
7. Handle missing or invalid values.
8. Create a clean final DataFrame.

At the end of the notebook, there is a full solution. Try the practice section first before looking at the solution.

In [5]:
import pandas as pd
import numpy as np

In [6]:
# Run this cell to create the messy dataset

data = {
    " Student ID ": [101, 102, 103, 104, 105, 106, 106, 107, 108, 109, 110, 111],
    "Name ": [
        "Ava Johnson", "liam smith", "MIA Chen", "Noah Davis", "Emma Brown",
        "Olivia Wilson", "Olivia Wilson", "James Taylor", "Sophia Lee",
        "Benjamin Martin", "Charlotte Clark", "Lucas Hall"
    ],
    "Age": ["19", "20", "eighteen", "21", np.nan, "22", "22", "19", "20", "twenty", "21", "18"],
    "Major": [
        "Data Science", "data science", "Computer Science", "Comp Sci", "Statistics",
        "statistics", "statistics", "DATA SCIENCE", "Computer science",
        "", "Math", "Mathematics"
    ],
    "Hours Studied": ["5", " 7 ", "three", "10", "8", "6", "6", np.nan, "4", "9", "11", "2"],
    "Exam Score": [88, 91, 76, 95, "missing", 84, 84, 72, 89, 93, 97, 65],
    "Submitted Assignment": ["Yes", "yes", "Y", "No", "N", "Yes", "Yes", "no", "", "Y", "Yes", "No"],
    "Date Submitted": [
        "2026-01-12", "01/13/2026", "2026/01/14", "not submitted", "",
        "2026-01-16", "2026-01-16", "2026-01-18", "Jan 19 2026",
        "2026-01-20", "2026-01-21", None
    ]
}

df = pd.DataFrame(data)
df

,Student ID,Name,Age,Major,Hours Studied,Exam Score,Submitted Assignment,Date Submitted
0,101,Ava Johnson,19,Data Science,5,88,Yes,2026-01-12
1,102,liam smith,20,data science,7,91,yes,01/13/2026
2,103,MIA Chen,eighteen,Computer Science,three,76,Y,2026/01/14
3,104,Noah Davis,21,Comp Sci,10,95,No,not submitted
4,105,Emma Brown,NaN,Statistics,8,missing,N,
5,106,Olivia Wilson,22,statistics,6,84,Yes,2026-01-16
6,106,Olivia Wilson,22,statistics,6,84,Yes,2026-01-16
7,107,James Taylor,19,DATA SCIENCE,NaN,72,no,2026-01-18
8,108,Sophia Lee,20,Computer science,4,89,,Jan 19 2026
9,109,Benjamin Martin,twenty,,9,93,Y,2026-01-20
10,110,Charlotte Clark,21,Math,11,97,Yes,2026-01-21
11,111,Lucas Hall,18,Mathematics,2,65,No,None

### Practice Task 1
Display the first few rows of the dataset.

In [20]:
# Your code here
df.head()
df

,Student ID,Name,Age,Major,Hours Studied,Exam Score,Submitted Assignment,Date Submitted
0,101,Ava Johnson,19,Data Science,5,88,Yes,2026-01-12
1,102,liam smith,20,data science,7,91,yes,01/13/2026
2,103,MIA Chen,eighteen,Computer Science,three,76,Y,2026/01/14
3,104,Noah Davis,21,Comp Sci,10,95,No,not submitted
4,105,Emma Brown,NaN,Statistics,8,missing,N,
5,106,Olivia Wilson,22,statistics,6,84,Yes,2026-01-16
6,106,Olivia Wilson,22,statistics,6,84,Yes,2026-01-16
7,107,James Taylor,19,DATA SCIENCE,NaN,72,no,2026-01-18
8,108,Sophia Lee,20,Computer science,4,89,,Jan 19 2026
9,109,Benjamin Martin,twenty,,9,93,Y,2026-01-20
10,110,Charlotte Clark,21,Math,11,97,Yes,2026-01-21
11,111,Lucas Hall,18,Mathematics,2,65,No,None

### Practice Task 2
Check the shape, column names, and data types.

In [22]:
# Your code here
df.shape
df.columns
df.dtypes
df

,Student ID,Name,Age,Major,Hours Studied,Exam Score,Submitted Assignment,Date Submitted
0,101,Ava Johnson,19,Data Science,5,88,Yes,2026-01-12
1,102,liam smith,20,data science,7,91,yes,01/13/2026
2,103,MIA Chen,eighteen,Computer Science,three,76,Y,2026/01/14
3,104,Noah Davis,21,Comp Sci,10,95,No,not submitted
4,105,Emma Brown,NaN,Statistics,8,missing,N,
5,106,Olivia Wilson,22,statistics,6,84,Yes,2026-01-16
6,106,Olivia Wilson,22,statistics,6,84,Yes,2026-01-16
7,107,James Taylor,19,DATA SCIENCE,NaN,72,no,2026-01-18
8,108,Sophia Lee,20,Computer science,4,89,,Jan 19 2026
9,109,Benjamin Martin,twenty,,9,93,Y,2026-01-20
10,110,Charlotte Clark,21,Math,11,97,Yes,2026-01-21
11,111,Lucas Hall,18,Mathematics,2,65,No,None

### Practice Task 3
Clean the column names (lowercase, strip, underscores).

In [24]:
# Your code here
df.columns = df.columns
df.columns = df.columns.str.strip()
df.columns = df.columns.str.lower()
df.columns = df.columns.str.replace(" " , " ")
df.columns
df

,student id,name,age,major,hours studied,exam score,submitted assignment,date submitted
0,101,Ava Johnson,19,Data Science,5,88,Yes,2026-01-12
1,102,liam smith,20,data science,7,91,yes,01/13/2026
2,103,MIA Chen,eighteen,Computer Science,three,76,Y,2026/01/14
3,104,Noah Davis,21,Comp Sci,10,95,No,not submitted
4,105,Emma Brown,NaN,Statistics,8,missing,N,
5,106,Olivia Wilson,22,statistics,6,84,Yes,2026-01-16
6,106,Olivia Wilson,22,statistics,6,84,Yes,2026-01-16
7,107,James Taylor,19,DATA SCIENCE,NaN,72,no,2026-01-18
8,108,Sophia Lee,20,Computer science,4,89,,Jan 19 2026
9,109,Benjamin Martin,twenty,,9,93,Y,2026-01-20
10,110,Charlotte Clark,21,Math,11,97,Yes,2026-01-21
11,111,Lucas Hall,18,Mathematics,2,65,No,None

### Practice Task 4
Remove duplicate rows.

In [27]:
# Your code here
df.drop_duplicates()
df

,student id,name,age,major,hours studied,exam score,submitted assignment,date submitted
0,101,Ava Johnson,19,Data Science,5,88,Yes,2026-01-12
1,102,liam smith,20,data science,7,91,yes,01/13/2026
2,103,MIA Chen,eighteen,Computer Science,three,76,Y,2026/01/14
3,104,Noah Davis,21,Comp Sci,10,95,No,not submitted
4,105,Emma Brown,NaN,Statistics,8,missing,N,
5,106,Olivia Wilson,22,statistics,6,84,Yes,2026-01-16
6,106,Olivia Wilson,22,statistics,6,84,Yes,2026-01-16
7,107,James Taylor,19,DATA SCIENCE,NaN,72,no,2026-01-18
8,108,Sophia Lee,20,Computer science,4,89,,Jan 19 2026
9,109,Benjamin Martin,twenty,,9,93,Y,2026-01-20
10,110,Charlotte Clark,21,Math,11,97,Yes,2026-01-21
11,111,Lucas Hall,18,Mathematics,2,65,No,None

### Practice Task 5
Clean the name column to title case.

In [28]:
# Your code here
df["name"] = df["name"].str.title()
df

,student id,name,age,major,hours studied,exam score,submitted assignment,date submitted
0,101,Ava Johnson,19,Data Science,5,88,Yes,2026-01-12
1,102,Liam Smith,20,data science,7,91,yes,01/13/2026
2,103,Mia Chen,eighteen,Computer Science,three,76,Y,2026/01/14
3,104,Noah Davis,21,Comp Sci,10,95,No,not submitted
4,105,Emma Brown,NaN,Statistics,8,missing,N,
5,106,Olivia Wilson,22,statistics,6,84,Yes,2026-01-16
6,106,Olivia Wilson,22,statistics,6,84,Yes,2026-01-16
7,107,James Taylor,19,DATA SCIENCE,NaN,72,no,2026-01-18
8,108,Sophia Lee,20,Computer science,4,89,,Jan 19 2026
9,109,Benjamin Martin,twenty,,9,93,Y,2026-01-20
10,110,Charlotte Clark,21,Math,11,97,Yes,2026-01-21
11,111,Lucas Hall,18,Mathematics,2,65,No,None

### Practice Task 6
Standardize the major column and handle blanks.

In [30]:
# Your code here
df["major"] = df["major"].str.strip()
df["major"] = df["major"].str.lower()
df["major"] = df["major"].str.replace(" ", " ")
df

,student id,name,age,major,hours studied,exam score,submitted assignment,date submitted
0,101,Ava Johnson,19,data science,5,88,Yes,2026-01-12
1,102,Liam Smith,20,data science,7,91,yes,01/13/2026
2,103,Mia Chen,eighteen,computer science,three,76,Y,2026/01/14
3,104,Noah Davis,21,comp sci,10,95,No,not submitted
4,105,Emma Brown,NaN,statistics,8,missing,N,
5,106,Olivia Wilson,22,statistics,6,84,Yes,2026-01-16
6,106,Olivia Wilson,22,statistics,6,84,Yes,2026-01-16
7,107,James Taylor,19,data science,NaN,72,no,2026-01-18
8,108,Sophia Lee,20,computer science,4,89,,Jan 19 2026
9,109,Benjamin Martin,twenty,,9,93,Y,2026-01-20
10,110,Charlotte Clark,21,math,11,97,Yes,2026-01-21
11,111,Lucas Hall,18,mathematics,2,65,No,None

### Practice Task 7
Convert age, hours_studied, and exam_score to numeric.

In [40]:
df["age"] = pd.to_numeric(df["age"], errors ="coerce")
df["hours studied"] = pd.to_numeric(df["hours studied"], errors= "coerce")
df["exam score"] = pd.to_numeric(df["exam score"], errors= "coerce")
df

,student id,name,age,major,hours studied,exam score,submitted assignment,date submitted
0,101,Ava Johnson,19.0,data science,5.0,88.0,Yes,2026-01-12
1,102,Liam Smith,20.0,data science,7.0,91.0,yes,01/13/2026
2,103,Mia Chen,NaN,computer science,NaN,76.0,Y,2026/01/14
3,104,Noah Davis,21.0,comp sci,10.0,95.0,No,not submitted
4,105,Emma Brown,NaN,statistics,8.0,NaN,N,
5,106,Olivia Wilson,22.0,statistics,6.0,84.0,Yes,2026-01-16
6,106,Olivia Wilson,22.0,statistics,6.0,84.0,Yes,2026-01-16
7,107,James Taylor,19.0,data science,NaN,72.0,no,2026-01-18
8,108,Sophia Lee,20.0,computer science,4.0,89.0,,Jan 19 2026
9,109,Benjamin Martin,NaN,,9.0,93.0,Y,2026-01-20
10,110,Charlotte Clark,21.0,math,11.0,97.0,Yes,2026-01-21
11,111,Lucas Hall,18.0,mathematics,2.0,65.0,No,None

### Practice Task 8
Clean submitted_assignment values.

In [45]:
# Your code here
df["submitted_assignment"] = df["submitted assignment"].astype(str).str.strip()
df["submitted_assignment"] = df["submitted assignment"].astype(str).str.lower()
df["submitted_assignment"]
df

,student id,name,age,major,hours studied,exam score,submitted assignment,date submitted,submitted_assignment
0,101,Ava Johnson,19.0,data science,5.0,88.0,Yes,2026-01-12,yes
1,102,Liam Smith,20.0,data science,7.0,91.0,yes,01/13/2026,yes
2,103,Mia Chen,NaN,computer science,NaN,76.0,Y,2026/01/14,y
3,104,Noah Davis,21.0,comp sci,10.0,95.0,No,not submitted,no
4,105,Emma Brown,NaN,statistics,8.0,NaN,N,,n
5,106,Olivia Wilson,22.0,statistics,6.0,84.0,Yes,2026-01-16,yes
6,106,Olivia Wilson,22.0,statistics,6.0,84.0,Yes,2026-01-16,yes
7,107,James Taylor,19.0,data science,NaN,72.0,no,2026-01-18,no
8,108,Sophia Lee,20.0,computer science,4.0,89.0,,Jan 19 2026,
9,109,Benjamin Martin,NaN,,9.0,93.0,Y,2026-01-20,y
10,110,Charlotte Clark,21.0,math,11.0,97.0,Yes,2026-01-21,yes
11,111,Lucas Hall,18.0,mathematics,2.0,65.0,No,None,no

### Practice Task 9
Convert date_submitted to datetime.

In [48]:
df["date_submitted"] = pd.to_datetime(df["date submitted"], errors= "coerce", format="mixed" )
df

,student id,name,age,major,hours studied,exam score,submitted assignment,date submitted,submitted_assignment,date_submitted
0,101,Ava Johnson,19.0,data science,5.0,88.0,Yes,2026-01-12,yes,2026-01-12
1,102,Liam Smith,20.0,data science,7.0,91.0,yes,01/13/2026,yes,2026-01-13
2,103,Mia Chen,NaN,computer science,NaN,76.0,Y,2026/01/14,y,2026-01-14
3,104,Noah Davis,21.0,comp sci,10.0,95.0,No,not submitted,no,NaT
4,105,Emma Brown,NaN,statistics,8.0,NaN,N,,n,NaT
5,106,Olivia Wilson,22.0,statistics,6.0,84.0,Yes,2026-01-16,yes,2026-01-16
6,106,Olivia Wilson,22.0,statistics,6.0,84.0,Yes,2026-01-16,yes,2026-01-16
7,107,James Taylor,19.0,data science,NaN,72.0,no,2026-01-18,no,2026-01-18
8,108,Sophia Lee,20.0,computer science,4.0,89.0,,Jan 19 2026,,2026-01-19
9,109,Benjamin Martin,NaN,,9.0,93.0,Y,2026-01-20,y,2026-01-20
10,110,Charlotte Clark,21.0,math,11.0,97.0,Yes,2026-01-21,yes,2026-01-21
11,111,Lucas Hall,18.0,mathematics,2.0,65.0,No,None,no,NaT

### Practice Task 10
Handle missing values (drop exam_score missing, fill hours median, major='Undeclared').

In [16]:
# Your code here

### Practice Task 11
Display the final cleaned DataFrame.

In [17]:
# Your code here

### Practice Task 12
Check final data types and missing values.

In [18]:
# Your code here

## Solution

In [19]:
clean_df = df.copy()

# Clean columns
clean_df.columns = clean_df.columns.str.strip().str.lower().str.replace(" ", "_")

# Drop duplicates
clean_df = clean_df.drop_duplicates()

# Clean names
clean_df["name"] = clean_df["name"].str.title()

# Clean major
clean_df["major"] = clean_df["major"].replace("", np.nan).str.strip().str.lower()
major_map = {
    "data science": "Data Science",
    "computer science": "Computer Science",
    "comp sci": "Computer Science",
    "statistics": "Statistics",
    "math": "Mathematics",
    "mathematics": "Mathematics"
}
clean_df["major"] = clean_df["major"].map(major_map)

# Convert numeric
clean_df["age"] = pd.to_numeric(clean_df["age"], errors="coerce")
clean_df["hours_studied"] = pd.to_numeric(clean_df["hours_studied"], errors="coerce")
clean_df["exam_score"] = pd.to_numeric(clean_df["exam_score"], errors="coerce")

# Clean submitted_assignment
clean_df["submitted_assignment"] = clean_df["submitted_assignment"].replace("", np.nan).str.strip().str.lower()
assignment_map = {"yes": "Yes", "y": "Yes", "no": "No", "n": "No"}
clean_df["submitted_assignment"] = clean_df["submitted_assignment"].map(assignment_map)

# Convert dates
clean_df["date_submitted"] = pd.to_datetime(clean_df["date_submitted"], errors="coerce", format="mixed")

# Handle missing
clean_df = clean_df.dropna(subset=["exam_score"])
clean_df["hours_studied"] = clean_df["hours_studied"].fillna(clean_df["hours_studied"].median())
clean_df["major"] = clean_df["major"].fillna("Undeclared")

clean_df

,student_id,name,age,major,hours_studied,exam_score,submitted_assignment,date_submitted
0,101,Ava Johnson,19.0,Data Science,5.0,88.0,Yes,2026-01-12
1,102,Liam Smith,20.0,Data Science,7.0,91.0,Yes,2026-01-13
2,103,Mia Chen,NaN,Computer Science,6.5,76.0,Yes,2026-01-14
3,104,Noah Davis,21.0,Computer Science,10.0,95.0,No,NaT
5,106,Olivia Wilson,22.0,Statistics,6.0,84.0,Yes,2026-01-16
7,107,James Taylor,19.0,Data Science,6.5,72.0,No,2026-01-18
8,108,Sophia Lee,20.0,Computer Science,4.0,89.0,NaN,2026-01-19
9,109,Benjamin Martin,NaN,Undeclared,9.0,93.0,Yes,2026-01-20
10,110,Charlotte Clark,21.0,Mathematics,11.0,97.0,Yes,2026-01-21
11,111,Lucas Hall,18.0,Mathematics,2.0,65.0,No,NaT